/**
 * APIエラーコード
 * フロントエンドで多言語対応するための識別子
 */
export enum ErrorCode {
  // --- 400 Bad Request: 入力不備系 ---
  VALIDATION_FAILED = "VALIDATION_FAILED", // DTOバリデーションエラーなど
  INVALID_PARAMETER = "INVALID_PARAMETER", // パラメータが無効

  MISSING_PARAMETER = "MISSING_PARAMETER", // パラメータが不足している

  // --- 401 Unauthorized / 403 Forbidden: 認証・権限系 ---
  // 基本的に401/403はステータスコードだけで十分だが、詳細な理由が必要な場合に利用
  PERMISSION_DENIED = "PERMISSION_DENIED", // リソースへのアクセス権がない

  // --- 404 Not Found: リソース不在 ---
  // 基本的に404はステータスコードだけで十分
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // --- 500 Internal Server Error: サーバー内部エラー ---
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR", // 予期せぬエラー

  DOCUMENTS_FILE_TOO_LARGE = "DOCUMENTS_FILE_TOO_LARGE", // ファイルサイズが大きすぎる
  DOCUMENTS_UNSUPPORTED_FILE_TYPE = "DOCUMENTS_UNSUPPORTED_FILE_TYPE", // サポートされていないファイルタイプ
  DOCUMENTS_INVALID_FILENAME_LENGTH_LIMIT = "DOCUMENTS_INVALID_FILENAME_LENGTH_LIMIT", // ファイル名の文字列制限
  DOCUMENTS_TAG_LENGTH_LIMIT = "DOCUMENTS_TAG_LENGTH_LIMIT", // タグの文字列制限
  DOCUMENTS_TAGS_TOO_MANY = "DOCUMENTS_TAGS_TOO_MANY", // タグが多すぎる
  DOCUMENTS_NOT_FOUND = "DOCUMENTS_NOT_FOUND", // ドキュメントが見つからない
  DOCUMENTS_UPLOAD_FAILED = "DOCUMENTS_UPLOAD_FAILED", // アップロードに失敗した
  DOCUMENTS_NOT_READY_FOR_DOWNLOAD = "DOCUMENTS_NOT_READY_FOR_DOWNLOAD", // ダウンロード準備ができていない
  DOCUMENTS_FILENAME_EMPTY = "DOCUMENTS_FILENAME_EMPTY", // ファイル名が空
  DOCUMENTS_SELECTION_EMPTY = "DOCUMENTS_SELECTION_EMPTY", // ドキュメントが選択されていない
  DOCUMENTS_SELECTION_TOO_MANY = "DOCUMENTS_SELECTION_TOO_MANY", // ドキュメントが多すぎる
  DOCUMENTS_DUPLICATE_CONTENT = "DOCUMENTS_DUPLICATE_CONTENT", // 同一内容のドキュメントが既に存在する
  // Chat API エラー
  CHAT_SESSION_NAME_TOO_LONG = "CHAT_SESSION_NAME_TOO_LONG", // セッション名が長すぎ
  CHAT_SESSION_NAME_EMPTY = "CHAT_SESSION_NAME_EMPTY", // セッション名が空
  CHAT_QUERY_EMPTY = "CHAT_QUERY_EMPTY",
  CHAT_QUERY_TOO_LONG = "CHAT_QUERY_TOO_LONG",
  CHAT_COMMENT_TOO_LONG = "CHAT_COMMENT_TOO_LONG",
  CHAT_FEEDBACK_REASONS_INVALID = "CHAT_FEEDBACK_REASONS_INVALID",
  CHAT_FEEDBACK_REASONS_EMPTY = "CHAT_FEEDBACK_REASONS_EMPTY",
}
